### ISSUE TITLE
Extend component SDK for developing Reinforcement Learning

### ISSUE THREAD

**Issue by yrh012** [aica-technology/component-template#7]
In this task, my issue is to improve the component template by pre-configuring the `aica-package.toml` file for users developing RL-based components. 

Specifically, I plan to include a build-step dependency to install the RL policy components package. This will enable users to inherit from `RLBase` and utilize the RL SDK README as a guide for building new RL components.

**Comment by eeberhard** [comment]
Replaced by aica-technology/dynamic-components#472
